name: Terraform Apply

on:
  workflow_call:
    secrets:
      aws_role:
        required: true
    inputs:
      aws_region:
        required: true
        type: string

jobs:
  apply:
    name: 🚀 Terraform Apply
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.aws_role }}
          aws-region: ${{ inputs.aws_region }}

      - uses: hashicorp/setup-terraform@v3

      - uses: actions/download-artifact@v4
        with:
          name: tfplan

      - run: terraform apply -auto-approve tfplan
